package com.t20simulator.model;

/**
 * Represents one row of VENUE table.
 * Used by Dashboard add-venue dialog and Match Entry venue dropdown.
 */
public class Venue {
    // venueId is auto-generated by MySQL after insert.
    private int venueId;
    private String name;
    private String city;
    private int capacity;

    public Venue() {
    }

    public Venue(int venueId, String name, String city, int capacity) {
        this.venueId = venueId;
        this.name = name;
        this.city = city;
        this.capacity = capacity;
    }

    public int getVenueId() {
        return venueId;
    }

    public void setVenueId(int venueId) {
        this.venueId = venueId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public int getCapacity() {
        return capacity;
    }

    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }

    @Override
    public String toString() {
        // JComboBox displays venue name and city instead of object memory address.
        return name + " (" + city + ")";
    }
}
